networks:
  default:
    external: true
    name: docker-bridge
volumes:
  mariadb-data:
  node_modules:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: chatbot-api
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - DB_HOST=mariadb
      - DB_USER=n8n
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=n8n
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - mariadb

  mariadb:
    image: jc21/mariadb-aria:latest
    container_name: mariadb
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=n8n
      - MYSQL_USER=n8n
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MARIADB_AUTO_UPGRADE="1"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./src/db/database-setup.sql:/docker-entrypoint-initdb.d/database-setup.sql
    ports:
      - 3306:3306
