secrets:
  DB_ROOT_PWD:
    file: ./.secrets/db_root_pwd.txt
  MYSQL_PWD:
    file: ./.secrets/mysql_pwd.txt
networks:
  default:
    external: true
    name: docker-bridge
volumes:
  mariadb-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: chatbot-api
    restart: unless-stopped
    secrets:
      - DB_ROOT_PWD
      - MYSQL_PWD
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=5000
      - API_KEY=${API_KEY}
      - DB_HOST=mariadb
      - DB_USER=n8n
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=n8n
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - mariadb

  mariadb:
    image: jc21/mariadb-aria:latest
    container_name: mariadb
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    secrets:
      - DB_ROOT_PWD
      - MYSQL_PWD
    environment:
      - MYSQL_ROOT_PASSWORD__FILE=/run/secrets/DB_ROOT_PWD
      - MYSQL_DATABASE=n8n
      - MYSQL_USER=n8n
      - MYSQL_PASSWORD__FILE=/run/secrets/MYSQL_PWD
      - MARIADB_AUTO_UPGRADE="1"
      - TZ=Asia/Jakarta
    volumes:
      - ./src/db/database-setup.sql:/docker-entrypoint-initdb.d/database-setup.sql
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    environment:
      - TZ=Asia/Jakarta
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    ports:
      - 8081:80
    image: phpmyadmin
