# docker-compose.yml
# Docker Compose file for MariaDB database setup

version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: chatbot-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: n8n
      MYSQL_USER: secure_user
      MYSQL_PASSWORD: strong_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database-setup.sql:/docker-entrypoint-initdb.d/database-setup.sql
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: chatbot-phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data:
